# Generated by Django 6.1.1 on 2026-09-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('plano', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('nascimento', models.DateField()),
                ('frequencia', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicios', models.TextField()),
                ('series', models.IntegerField(max_length=3)),
                ('repeticoes', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('imc', models.IntegerField()),
                ('ficha_de_treino', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_modulo.aluno')),
            ],
        ),
    ]
