# Generated by Django 6.1.1 on 2026-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_modulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alunos',
            new_name='Aluno',
        ),
        migrations.AlterField(
            model_name='treino',
            name='idade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='treino',
            name='imc',
            field=models.CharField(max_length=20),
        ),
    ]
