# Generated by Django 6.1.1 on 2026-09-19 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='exercicios',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='series',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='treino',
            name='ficha_de_treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_modulo.ficha'),
        ),
    ]
