# Generated by Django 6.1.1 on 2026-09-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_modulo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='status',
        ),
    ]
