# Generated by Django 6.1.1 on 2026-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_modulo', '0002_alter_ficha_exercicios_alter_ficha_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='exercicios',
            field=models.CharField(max_length=100),
        ),
    ]
