# Generated by Django 6.1.1 on 2026-09-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_modulo', '0002_remove_aluno_frequencia_remove_aluno_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='exercicios',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='repeticoes',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='series',
        ),
    ]
