# Generated by Django 6.1.1 on 2026-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_modulo', '0002_rename_alunos_aluno_alter_treino_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='idade',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='treino',
            name='imc',
            field=models.IntegerField(max_length=3),
        ),
    ]
